#ifndef SWAY_GAPI_BLENDFUNCTIONS_HPP
#define SWAY_GAPI_BLENDFUNCTIONS_HPP

#include <sway/core.hpp>

namespace sway::gapi {

// clang-format off
#define BLEND_FUNCTION_LIST(ITEM) \
  ITEM(ZERO, 1) \
  ITEM(ONE, 2) \
  ITEM(SRC_COLOR, 3) \
  ITEM(ONE_MINUS_SRC_COLOR, 4) \
  ITEM(DST_COLOR, 5) \
  ITEM(ONE_MINUS_DST_COLOR, 6) \
  ITEM(SRC_ALPHA, 7) \
  ITEM(ONE_MINUS_SRC_ALPHA, 8) \
  ITEM(DST_ALPHA, 9) \
  ITEM(ONE_MINUS_DST_ALPHA, 10) \
  ITEM(SRC_ALPHA_SATURATE, 11)
// clang-format on

DECLARE_ENUM_U32(BlendFn, BLEND_FUNCTION_LIST)

}  // namespace sway::gapi

#endif  // SWAY_GAPI_BLENDFUNCTIONS_HPP
