#ifndef SWAY_GAPI_BUFFERMAPACCESSES_HPP
#define SWAY_GAPI_BUFFERMAPACCESSES_HPP

#include <sway/core.hpp>

NAMESPACE_BEGIN(sway)
NAMESPACE_BEGIN(gapi)

enum class BufferMapAccess : u32_t { UNDEF = 0, READ, WRITE, READ_WRITE, Latest };

NAMESPACE_END(gapi)
NAMESPACE_END(sway)

#endif  // SWAY_GAPI_BUFFERMAPACCESSES_HPP
