#ifndef SWAY_GAPI_FRONTFACES_HPP
#define SWAY_GAPI_FRONTFACES_HPP

#include <sway/core.hpp>

NAMESPACE_BEGIN(sway)
NAMESPACE_BEGIN(gapi)

enum class FrontFace { NONE = 0, CLOCK_WISE, COUNTER_CLOCK_WISE, Latest };

NAMESPACE_END(gapi)
NAMESPACE_END(sway)

#endif  // SWAY_GAPI_FRONTFACES_HPP
