#ifndef SWAY_GAPI_PIXELSTORAGEMODES_HPP
#define SWAY_GAPI_PIXELSTORAGEMODES_HPP

#include <sway/core.hpp>

NAMESPACE_BEGIN(sway)
NAMESPACE_BEGIN(gapi)

enum class PixelStorageMode : u32_t { UNDEF, UNPACK_ALIGNMENT, UNPACK_ROW_LENGTH };

NAMESPACE_END(gapi)
NAMESPACE_END(sway)

#endif  // SWAY_GAPI_PIXELSTORAGEMODES_HPP
