#ifndef SWAY_GAPI_PIXELSTORAGEMODES_HPP
#define SWAY_GAPI_PIXELSTORAGEMODES_HPP

#include <sway/core.hpp>

NS_BEGIN_SWAY()
NS_BEGIN(gapi)

DECLARE_ENUM(PixelStorageMode, UNPACK_ALIGNMENT, UNPACK_ROW_LENGTH);

NS_END()  // namespace gapi
NS_END()  // namespace sway

#endif  // SWAY_GAPI_PIXELSTORAGEMODES_HPP
