#ifndef SWAY_GAPI_STATECAPABILITIES_HPP
#define SWAY_GAPI_STATECAPABILITIES_HPP

#include <sway/core.hpp>

NAMESPACE_BEGIN(sway)
NAMESPACE_BEGIN(gapi)

enum class StateCapability : u32_t {
  NONE = 0,
  BLEND,
  RASTERIZER,
  CULL_FACE,
  DEPTH_TEST,
  SCISSOR_TEST,
  STENCIL_TEST,
  Latest
};

NAMESPACE_END(gapi)
NAMESPACE_END(sway)

#endif  // SWAY_GAPI_STATECAPABILITIES_HPP
