#ifndef SWAY_GAPI_STATEENABLEABLE_HPP
#define SWAY_GAPI_STATEENABLEABLE_HPP

#include <sway/core.hpp>

NAMESPACE_BEGIN(sway)
NAMESPACE_BEGIN(gapi)

struct StateEnableable {};

NAMESPACE_END(gapi)
NAMESPACE_END(sway)

#endif  // SWAY_GAPI_STATEENABLEABLE_HPP
