#ifndef SWAY_GAPI_STATECAPABILITIES_HPP
#define SWAY_GAPI_STATECAPABILITIES_HPP

#include <sway/core.hpp>

NAMESPACE_BEGIN(sway)
NAMESPACE_BEGIN(gapi)

enum class StateCapability : u32_t {
  BLEND = 0,  // GL_BLEND
  RASTERIZER,
  CULL_FACE,  // GL_CULL_FACE
  DEPTH_TEST,  // GL_DEPTH_TEST
  SCISSOR_TEST,  // GL_SCISSOR_TEST
  STENCIL_TEST,  // GL_STENCIL_TEST
  Latest,
  UNDEF
};

NAMESPACE_END(gapi)
NAMESPACE_END(sway)

#endif  // SWAY_GAPI_STATECAPABILITIES_HPP
