#ifndef SWAY_GAPI_TEXTURETARGETS_HPP
#define SWAY_GAPI_TEXTURETARGETS_HPP

#include <sway/core.hpp>

NAMESPACE_BEGIN(sway)
NAMESPACE_BEGIN(gapi)

enum class TextureTarget : u32_t {
  TEX_2D,
  TEX_2D_ARRAY,
  MULTISAMPLE,
  MULTISAMPLE_ARRAY,
  RECT,
  CUBE_MAP,

  Unknown,
  Latest
};

NAMESPACE_END(gapi)
NAMESPACE_END(sway)

#endif  // SWAY_GAPI_TEXTURETARGETS_HPP
