#ifndef SWAY_GAPI_TEXTURETARGETS_HPP
#define SWAY_GAPI_TEXTURETARGETS_HPP

#include <sway/core.hpp>

NS_BEGIN_SWAY()
NS_BEGIN(gapi)

DECLARE_ENUM(TextureTarget, TEX_2D, TEX_2D_ARRAY, MULTISAMPLE, MULTISAMPLE_ARRAY, RECT, CUBE_MAP);

NS_END()  // namespace gapi
NS_END()  // namespace sway

#endif  // SWAY_GAPI_TEXTURETARGETS_HPP
